name: Send Daily PTO Notification

on:
  schedule:
    - cron: '0 9 * * 1-5'
  # workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Ruby 3.0.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true

      - name: Run script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          PTO_CALENDAR_ID: ${{ secrets.PTO_CALENDAR_ID }}
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: ruby ./main.rb
